# Generated by Django 4.2.5 on 2023-11-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProposalSection',
            new_name='ProposalSectionForm',
        ),
    ]
