# Generated by Django 4.2.5 on 2023-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_proposalsection_proposalsectionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
