# Generated by Django 4.2.5 on 2023-11-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_proposal_is_saved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saved_proposals',
        ),
    ]
