# Generated by Django 4.2.5 on 2023-11-03 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
